In [21]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [17]:
df_test = pd.read_csv("test.csv")
df_test = df_test.drop(["Id", "index"], axis=1)
df_test.head()

,pdb_chain,DSSR,xray,resol,chainlen,protein,alpham2,betam2,gammam2,deltam2,...,atomO2,atomO2p,atomO3p,atomO4,atomO4p,atomO5p,atomO6,atomOP1,atomOP2,atomOP3
0,1feu.cif1_F,F.C.93.,1,2.3,21,1,-73.3,174.9,53.7,83.5,...,0,0,0,0,0,0,0,1,0,0
1,1feu.cif1_F,F.C.93.,1,2.3,21,1,-73.3,174.9,53.7,83.5,...,0,0,0,0,0,0,0,0,1,0
2,1feu.cif1_F,F.C.93.,1,2.3,21,1,-73.3,174.9,53.7,83.5,...,0,0,0,0,0,1,0,0,0,0
3,1feu.cif1_F,F.C.93.,1,2.3,21,1,-73.3,174.9,53.7,83.5,...,0,0,0,0,1,0,0,0,0,0
4,1feu.cif1_F,F.C.93.,1,2.3,21,1,-73.3,174.9,53.7,83.5,...,0,0,1,0,0,0,0,0,0,0

In [6]:
df_train = pd.read_csv("train.csv", sep="\t")
df_train.head()

,pdb_chain,DSSR,xray,resol,chainlen,protein,alpham2,betam2,gammam2,deltam2,...,atomO2p,atomO3p,atomO4,atomO4p,atomO5p,atomO6,atomOP1,atomOP2,atomOP3,mg
0,1b23.cif1_R,R.G.1.,1,2.6,74,1,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,1,0
1,1b23.cif1_R,R.G.1.,1,2.6,74,1,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,0
2,1b23.cif1_R,R.G.1.,1,2.6,74,1,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,1,0,0
3,1b23.cif1_R,R.G.1.,1,2.6,74,1,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,0,0,0
4,1b23.cif1_R,R.G.1.,1,2.6,74,1,NaN,NaN,NaN,NaN,...,0,0,0,1,0,0,0,0,0,0

In [18]:
df_train.shape, df_test.shape

((237969, 386), (4045, 385))

In [23]:
X_train = df_train[df_train.columns[:-1]].values

MemoryError: